version: '3.8'

services:

  mongo:
    image: mongo:4.4.6 
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  server:
    image: backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3001
    environment:
      - MONGO_URI=mongodb://the_username:the_password@mongo:27017/the_database
      - PORT=3001
    container_name: bloglist-backend-dev